# -*- coding: utf-8 -*-
"""CNNNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ouOMCygyunpPaq9OA1ATPCdwf61gn75z
"""

from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

# Initializing the CNN
classifier  = Sequential()

# # Importing the dataset
from google.colab import drive
drive.mount('/content/gdrive')

# Step1: Convolution- creating feature map
classifier.add(Convolution2D(32,3,3,input_shape=(64,64,3),activation='relu'))

# step2: Pooling- reducing the size of mat.
classifier.add(MaxPooling2D(pool_size=(2,2)))

# Step3: Flattening single vector.
classifier.add(Flatten())

# step4: Full connection
classifier.add(Dense(128,activation='relu'))
classifier.add(Dense(1,activation='sigmoid'))

# compiling all
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

# fitting the CNN to the image
from keras.preprocessing.image import ImageDataGenerator
train_datagen = ImageDataGenerator(
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)

test_datagen = ImageDataGenerator(rescale=1./255)

training_set = train_datagen.flow_from_directory(
        '/content/gdrive/My Drive/Pothole_Image_Data/train',
        target_size=(64, 64),
        batch_size=10,
        class_mode='binary')

test_set = test_datagen.flow_from_directory(
        '/content/gdrive/My Drive/Pothole_Image_Data/test',
        target_size=(64, 64),
        batch_size=10,
        class_mode='binary')

classifier.fit_generator(training_set,epochs = 10,validation_data = test_set,validation_steps = 100)